---
- name: Configure Docker and deploy Flask app on Azure VM
  hosts: azure_vm
  become: yes
  vars:
    docker_image: "khushi2111/flask_app:latest"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - python3-setuptools
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Install Docker SDK for Python
      pip:
        name:
          - docker
          - packaging
        executable: pip3

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Stop and remove existing container
      docker_container:
        name: webapp
        state: absent

    - name: Deploy Flask container
      docker_container:
        name: webapp
        image: "{{ docker_image }}"
        ports:
          - "80:80"
        restart_policy: always
        state: started

    - name: Verify container status
      docker_container_info:
        name: webapp
      register: container_info

    - name: Check web service availability
      uri:
        url: "http://localhost:80"
        method: GET
        status_code: 200
      register: webapp_response
      until: webapp_response.status == 200
      retries: 5
      delay: 2

    - name: Display deployment information
      debug:
        msg:
          - "=== Deployment Complete ==="
          - "Access your Flask app at: http://{{ ansible_host }}:80"
          - "Container ID: {{ container_info.container.Id }}"
          - "Container Status: {{ container_info.container.State.Status }}"