name: CI/CD Build and Deploy

on:
  push:
    branches:
      [main]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/webapp:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE ./sample-application

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/webapp:latest
      PUBLIC_IP: ${{ secrets.AZURE_VM_PUBLIC_IP }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible & dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-pip
          pip3 install docker packaging

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Generate dynamic inventory
        run: |
         echo "[azure_vm]" > inventory.ini
         echo "${{ secrets.HOST }} ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3" >> inventory.ini

      - name: Run Ansible Playbook 
        run: |
          ansible-playbook -i inventory.ini ansible/docker.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

     # - name: Run Ansible Playbook
      #  run: |
       #   ansible-playbook \
        #    -i "${PUBLIC_IP}," \
         #   -u azureuser \
          #  --private-key ~/.ssh/id_rsa \
           # -e "docker_image=${DOCKER_IMAGE}" \
            #ansible/docker.yml
    #    env:
     #     ANSIBLE_HOST_KEY_CHECKING: "False"
