name: Azure Deployment Pipeline

on: 
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_infrastructure:
        description: 'Deploy infrastructure (use only for initial setup or infrastructure changes)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/webapp:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE ./sample-application
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push Docker image
        run: docker push $DOCKER_IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_infrastructure == 'true') || 
      (github.event_name == 'push' && contains(github.event.head_commit.message, '[infra]'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
      - name: Azure Login with Retry
        run: |
          for i in {1..3}; do
            echo "Login attempt $i"
            if az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}; then
              echo "Login successful"
              break
            else
              echo "Login failed, retrying..."
              sleep 10
            fi
          done
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Write SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa*

      - name: Terraform Init & Apply
        run: |
          cd ./terraform
          terraform init
          terraform apply -auto-approve
        env:
          ARM_USE_CLI: true

      - name: Get Public IP
        run: |
          cd ./terraform
          IP=$(terraform output -raw public_ip)
          echo "PUBLIC_IP=$IP" >> $GITHUB_ENV
          echo "Deployed to IP: $IP"

      - name: Setup Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook \
            -i "${PUBLIC_IP}," \
            -u azureuser \
            --private-key ~/.ssh/id_rsa \
            -e "docker_image=${DOCKER_IMAGE}" \
            ansible/docker.yml
        env:
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          PUBLIC_IP: ${{ env.PUBLIC_IP }}
          ANSIBLE_HOST_KEY_CHECKING: "False"

  deploy-app-only:
    needs: build
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_infrastructure == 'false') || 
      (github.event_name == 'push' && !contains(github.event.head_commit.message, '[infra]'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        run: |
          az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Write SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa*

      - name: Get Public IP from existing resources
        run: |
          if [ -n "${{ secrets.AZURE_VM_PUBLIC_IP }}" ]; then
            PUBLIC_IP="${{ secrets.AZURE_VM_PUBLIC_IP }}"
            echo "Using stored IP from secrets: $PUBLIC_IP"
          else
            PUBLIC_IP=$(az vm list-ip-addresses --query "[0].virtualMachine.network.publicIpAddresses[0].ipAddress" -o tsv)
          fi
          if [ -z "$PUBLIC_IP" ] || [ "$PUBLIC_IP" = "null" ]; then
            echo "ERROR: Could not retrieve public IP address"
            exit 1
          fi
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          echo "Deploying to IP: $PUBLIC_IP"

      - name: Setup Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook \
            -i "${PUBLIC_IP}," \
            -u azureuser \
            --private-key ~/.ssh/id_rsa \
            -e "docker_image=${DOCKER_IMAGE}" \
            ansible/docker.yml
        env:
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          PUBLIC_IP: ${{ env.PUBLIC_IP }}
          ANSIBLE_HOST_KEY_CHECKING: "False"
