name: Deploy Flask App to Azure VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible sshpass

    - name: Add SSH Key
      run: |
        echo "${{ secrets.SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Create Inventory File
      run: |
        echo "[azure_vm]" > inventory
        echo "${{ secrets.HOST }} ansible_user=azureuser ansible_ssh_private_key_file=./key.pem" >> inventory

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory ansible/docker.yml
