name: Azure Deployment Pipeline

on: [push]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Debug Docker image name
        run: |
          echo "Docker image will be: $DOCKER_IMAGE"
          echo "Docker username: ${{ secrets.DOCKER_USERNAME }}"
          echo "GitHub SHA: ${{ github.sha }}"
      
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE ./sample-application
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image
        run: docker push $DOCKER_IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: Azure Login with Retry
        run: |
          for i in {1..3}; do
            echo "Login attempt $i"
            if az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}; then
              echo "Login successful"
              break
            else
              echo "Login failed, retrying..."
              sleep 10
            fi
          done
          
          # Set subscription
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
          # Verify
          echo "Current account:"
          az account show
      
      
      - name: Setup Ansible
        run: sudo apt update && sudo apt install -y ansible
      
      - name: Run Ansible Playbook
        run: |
          ansible-playbook \
            -i "${PUBLIC_IP}," \
            -u azureuser \
           --private-key ~/.ssh/id_rsa \
            -e "docker_image=${DOCKER_IMAGE}" \
            ansible/docker.yml
        env:
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          PUBLIC_IP: ${{ env.PUBLIC_IP }}  
          ANSIBLE_HOST_KEY_CHECKING: "False"