name: Ansible Remote Deployment

on:
  push:
    branches: [main]

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest

    env:
      PUBLIC_IP: ${{ secrets.HOST }}
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/webapp:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Ansible & dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible python3-pip
        pip3 install docker packaging

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Run Ansible Playbook
      run: |
        ansible-playbook \
          -i "${{ env.PUBLIC_IP }}," \
          -u azureuser \
          --private-key ~/.ssh/id_rsa \
          -e "docker_image=${{ env.DOCKER_IMAGE }}" \
          ansible/docker.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
